services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: medical_ai
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres

      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http

      N8N_CORS_ALLOW_ORIGIN: "http://127.0.0.1:5500"
      WEBHOOK_URL: "http://localhost:5678"

    depends_on:
      - postgres

volumes:
  postgres_data: